server:
  port: 8180
spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/eon?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/eon_2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: 禾冠平台
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format_sql: true
        enable_lazy_load_no_trans: false     #支持全局实体的懒加载，但开销很大
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  freemarker:
    request-context-attribute: req  #req访问request
    suffix:   #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  http:
    converters:
      preferred-json-mapper: fastjson
security:
  oauth2:
    client:
      clientId: cxj
      clientSecret: user
      userAuthorizationUri: http://localhost:8100/oauth/authorize
      grant-type: password
      scope: read
      access-token-uri: http://localhost:8100/oauth/token
    resource:
      token-info-uri: http://localhost:8100/oauth/check_token
      user-info-uri: http://localhost:8100/user
      #jwt:
      #  key-uri: http://localhost:8100/oauth/token_key
    authorization:
      check-token-access: http://localhost:8100/oauth/check_token
logging:
  level:
    root: error
  path: /usr/local/logs/spring
eon:
  hg:
    security:
      authType: session    #认证方式，session，token
      oauth2:
        storeType: redis    #jdbc，redis，jwt几种模式，需要与授权服务器一致
        resourceId: oauth2-resource
    async:
      corePoolSize : 10
      maxPoolSize : 200
      queueCapacity : 10
    hessian:
      server-url: http://127.0.0.1:8080/vcf/remote/
    file:
      upload_folder: /Users/aeon/Documents/uploadfile/

